#!/bin/bash
echo "Starting deployment actions"
#cp /opt/nepho/data/common/puppet/files/mod_auth_cas.conf /etc/httpd/conf.d/
mkdir /usr/share/tomcat6/webapps/castest
cp /opt/nepho/data/common/puppet/files/index.jsp /usr/share/tomcat6/webapps/castest/
ln -s /opt/nepho/data/common/puppet/files/mod_auth_cas.conf /etc/httpd/conf.d/mod_auth_cas.conf
mkdir /mod_auth_cas
chown apache:apache /mod_auth_cas
service httpd restart

exit 0
