#!/bin/bash
echo "Starting deployment actions"
cp /opt/nepho/data/common/puppet/files/mod_auth_cas.conf /etc/httpd/conf.d/
mkdir /mod_auth_cas
chown apache:apache /mod_auth_cas
service httpd restart

exit 0
